#!/usr/bin/env python3
"""Regenerates the bundled Raycast theme catalog from raycast/ray-so (MIT).

    python3 .space/tools/raycast-themes.py > /tmp/RaycastThemeCatalog.swift

Then fold the output into patch 0011 (it adds Tinycast/Features/Settings/RaycastThemeCatalog.swift).
"""
import json
import re
import sys
import urllib.parse
import urllib.request

REPO = "raycast/ray-so"
ROOT = "app/(navigation)/themes/themes/"
ORDER = ["background", "backgroundSecondary", "text", "selection", "loader",
         "red", "orange", "yellow", "green", "blue", "purple", "magenta"]


def get(url):
    with urllib.request.urlopen(url, timeout=30) as response:
        return response.read()


def swift_string(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def hex6(value):
    value = value.strip()
    if not re.fullmatch(r"#[0-9A-Fa-f]{6}([0-9A-Fa-f]{2})?", value):
        raise ValueError(value)
    return value[:7].upper()  # ray.so drops a legacy alpha pair the same way


sha = json.loads(get(f"https://api.github.com/repos/{REPO}/commits/main"))["sha"]
tree = json.loads(get(f"https://api.github.com/repos/{REPO}/git/trees/{sha}?recursive=1"))["tree"]
paths = sorted(e["path"] for e in tree if e["path"].startswith(ROOT) and e["path"].endswith(".json"))

themes = []
for path in paths:
    raw = get(f"https://raw.githubusercontent.com/{REPO}/{sha}/{urllib.parse.quote(path)}")
    data = json.loads(raw)
    if data.get("appearance") not in ("light", "dark"):
        print(f"skipping {path}: appearance", file=sys.stderr)
        continue
    try:
        colors = [hex6(data["colors"][key]) for key in ORDER]
    except (KeyError, ValueError) as error:
        print(f"skipping {path}: {error}", file=sys.stderr)
        continue
    themes.append((data["name"], data.get("author") or data.get("authorUsername") or "", data["appearance"], colors))

themes.sort(key=lambda t: (t[0].lower(), t[1].lower()))
license = get(f"https://raw.githubusercontent.com/{REPO}/{sha}/LICENSE").decode().strip()
out = [
    "// tinycast-space: generated by .space/tools/raycast-themes.py from",
    f"// github.com/{REPO} at {sha[:12]}, app/(navigation)/themes/themes. Do not edit.",
    "// The themes are ray.so's and their authors', under ray.so's license:",
    "//",
    *[("// " + line).rstrip() for line in license.splitlines()],
    "",
    "enum RaycastThemeCatalog {",
    "    static let all: [RaycastTheme] = [",
]
for name, author, appearance, colors in themes:
    out.append(
        f"        RaycastTheme(\n"
        f"            name: {swift_string(name)}, author: {swift_string(author)}, appearance: .{appearance},\n"
        f"            colors: [\n"
        f"                {', '.join(swift_string(c) for c in colors[:6])},\n"
        f"                {', '.join(swift_string(c) for c in colors[6:])}\n"
        f"            ]),"
    )
out += ["    ]", "}", ""]
sys.stdout.write("\n".join(out))
print(f"{len(themes)} themes from {REPO}@{sha[:7]}", file=sys.stderr)
