// tinycast-space: generated by .space/tools/raycast-themes.py from
// github.com/raycast/ray-so at 168f9aa9c2c4, app/(navigation)/themes/themes. Do not edit.
// The themes are ray.so's and their authors', under ray.so's license:
//
// MIT License
//
// Copyright (c) 2024 Raycast Technologies Ltd
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

enum RaycastThemeCatalog {
    static let all: [RaycastTheme] = [
        RaycastTheme(
            name: "Alex's Dark Blue 600", author: "Alex", appearance: .dark,
            colors: [
                "#0086C9", "#0B4A6F", "#E3E8EF", "#F8FAFC", "#F8FAFC", "#F99266",
                "#E05316", "#CA8504", "#039855", "#0BA5EC", "#6938EF", "#DD2590"
            ]),
        RaycastTheme(
            name: "Almost Cyan", author: "Chris", appearance: .dark,
            colors: [
                "#000A42", "#004282", "#FFFFFF", "#A8C1FF", "#00E2FF", "#F84141",
                "#FF6B17", "#FEFF7F", "#63BA89", "#6AB7FB", "#C58AFA", "#FF5DB3"
            ]),
        RaycastTheme(
            name: "Alpenglow", author: "Danny Seidel", appearance: .dark,
            colors: [
                "#003F71", "#9E0000", "#EEEEEE", "#FF7C43", "#5751A1", "#FF1111",
                "#F86D1C", "#FFC839", "#23F893", "#1686F6", "#7546F8", "#F847BA"
            ]),
        RaycastTheme(
            name: "Alucard", author: "Lucas de França", appearance: .light,
            colors: [
                "#FFFBEB", "#FFFBEB", "#1F1F1F", "#CFCFDE", "#6C664B", "#CB5A2A",
                "#A34D14", "#846E15", "#14710A", "#036A96", "#644AC9", "#A3144D"
            ]),
        RaycastTheme(
            name: "Arc", author: "Drew Andersen", appearance: .dark,
            colors: [
                "#520081", "#000026", "#DF87C5", "#FF13BB", "#DFBCD5", "#FF7F7F",
                "#DFB162", "#DFC320", "#9AFC00", "#086CFB", "#9940E0", "#FF00CE"
            ]),
        RaycastTheme(
            name: "Atom One Dark", author: "Macko++", appearance: .dark,
            colors: [
                "#282C34", "#282C34", "#C0C7D6", "#528BFF", "#528BFF", "#BE6A46",
                "#D19A66", "#E5C07B", "#98C379", "#61AFEF", "#C678DD", "#56B6C2"
            ]),
        RaycastTheme(
            name: "Atom One Light", author: "Daniel Hollick", appearance: .light,
            colors: [
                "#FAFAFA", "#E4E4E4", "#3E4047", "#457CEF", "#457CEF", "#E24343",
                "#E2612A", "#CAC235", "#56A156", "#1485BA", "#642EA4", "#A42EA2"
            ]),
        RaycastTheme(
            name: "Aura", author: "Shubh Porwal", appearance: .dark,
            colors: [
                "#15141B", "#15141B", "#EDECEE", "#A277FF", "#61FFCA", "#FF6767",
                "#FFCA85", "#FFD700", "#61FFCA", "#82E2FF", "#A277FF", "#F694FF"
            ]),
        RaycastTheme(
            name: "Ayu Mirage Owl 🦉", author: "Abhi Mehrotra", appearance: .dark,
            colors: [
                "#1F2430", "#FFAE57", "#A8D96E", "#C7A6FF", "#5CCFE6", "#FFA27A",
                "#FFAE57", "#FFCC66", "#A8D96E", "#5CCFE6", "#C7A6FF", "#FF9FD4"
            ]),
        RaycastTheme(
            name: "Barcelona Sky", author: "Chris", appearance: .light,
            colors: [
                "#C8D8FF", "#82A6FF", "#001958", "#2151C8", "#900DE2", "#EE3232",
                "#FA7E37", "#EBA200", "#30B475", "#0E3DD8", "#960EEB", "#DD0F95"
            ]),
        RaycastTheme(
            name: "Black Opal", author: "Sean Rose", appearance: .dark,
            colors: [
                "#000015", "#003399", "#FFFFFF", "#AE0DFF", "#00FAFF", "#FF0000",
                "#FF7F00", "#FFFF00", "#00FF00", "#0064FF", "#9932CD", "#EE82EE"
            ]),
        RaycastTheme(
            name: "Blossom", author: "Thomas Novaro", appearance: .light,
            colors: [
                "#F9EBE0", "#DFD0F7", "#0D0D0D", "#22A3A3", "#D56062", "#F56B6B",
                "#F59C69", "#FDCF57", "#57D499", "#4E85BC", "#8F6CF5", "#F56AC5"
            ]),
        RaycastTheme(
            name: "Blue Boy", author: "Pedro Duarte", appearance: .light,
            colors: [
                "#FFFFFF", "#FFFFFF", "#0000FF", "#004DFF", "#0000FF", "#E14848",
                "#E5753C", "#B7B400", "#00AC5D", "#4F80FF", "#9454FF", "#D756BF"
            ]),
        RaycastTheme(
            name: "Brutalist Dark", author: "Mathieu de Gouville", appearance: .dark,
            colors: [
                "#000000", "#000000", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FF0000",
                "#FFA500", "#FFFF00", "#00FF00", "#0000FF", "#800080", "#FF00FF"
            ]),
        RaycastTheme(
            name: "Brutalist Light", author: "Mathieu de Gouville", appearance: .light,
            colors: [
                "#FFFFFF", "#FFFFFF", "#000000", "#000000", "#000000", "#FF0000",
                "#FFA500", "#FFFF00", "#00FF00", "#0000FF", "#800080", "#FF00FF"
            ]),
        RaycastTheme(
            name: "Catppuccin Frappe", author: "Catppuccin", appearance: .dark,
            colors: [
                "#303446", "#303446", "#C6D0F5", "#737994", "#838BA7", "#E78284",
                "#EF9F76", "#E5C890", "#A6D189", "#8CAAEE", "#BABBF1", "#CA9EE6"
            ]),
        RaycastTheme(
            name: "Catppuccin Latte", author: "Catppuccin", appearance: .light,
            colors: [
                "#EFF1F5", "#EFF1F5", "#4C4F69", "#9CA0B0", "#8C8FA1", "#D20F39",
                "#FE640B", "#DF8E1D", "#40A02B", "#1E66F5", "#7287FD", "#8839EF"
            ]),
        RaycastTheme(
            name: "Catppuccin Macchiato", author: "Catppuccin", appearance: .dark,
            colors: [
                "#24273A", "#24273A", "#CAD3F5", "#6E738D", "#8087A2", "#ED8796",
                "#F5A97F", "#EED49F", "#A6DA95", "#8AADF4", "#B7BDF8", "#C6A0F6"
            ]),
        RaycastTheme(
            name: "Catppuccin Mocha", author: "Catppuccin", appearance: .dark,
            colors: [
                "#1E1E2E", "#1E1E2E", "#CDD6F4", "#6C7086", "#7F849C", "#F38BA8",
                "#FAB387", "#F9E2AF", "#A6E3A1", "#89B4FA", "#B4BEFE", "#CBA6F7"
            ]),
        RaycastTheme(
            name: "Catppuccin x Gruvbox", author: "Raf", appearance: .dark,
            colors: [
                "#000B12", "#000B12", "#D4BE98", "#BDAE8B", "#E84141", "#EA6262",
                "#BD6F3E", "#D8A657", "#A9B665", "#7DAEA3", "#7B4EF8", "#D3869B"
            ]),
        RaycastTheme(
            name: "Christmas Dark", author: "Ian Spryn", appearance: .dark,
            colors: [
                "#287E54", "#007E40", "#D5FFEA", "#F84E4E", "#F84E4E", "#F84E4E",
                "#F88D4E", "#FFCC47", "#4EF8A7", "#228CF6", "#7B4EF8", "#F84EBD"
            ]),
        RaycastTheme(
            name: "Christmas Light", author: "Ian Spryn", appearance: .light,
            colors: [
                "#3CBC7D", "#007E40", "#004321", "#FF5F5F", "#F84E4E", "#F50A0A",
                "#F5600A", "#E0A200", "#07BA65", "#007FFF", "#3107A8", "#F50AA3"
            ]),
        RaycastTheme(
            name: "Cobalt 2", author: "Wes Bos", appearance: .dark,
            colors: [
                "#065085", "#065085", "#FFFEFA", "#FFFFFF", "#FFC600", "#FF5757",
                "#FF9D00", "#FFC600", "#ACF4A5", "#83C7FB", "#A496FF", "#FF5AB2"
            ]),
        RaycastTheme(
            name: "Comfy", author: "Drew Andersen", appearance: .light,
            colors: [
                "#FEECDD", "#FEECDD", "#B03D0B", "#FF8500", "#8E9BFF", "#E82A90",
                "#FF6F31", "#FFD600", "#10FF33", "#1034FF", "#5906FF", "#FF277D"
            ]),
        RaycastTheme(
            name: "Dark+Cyan", author: "Chris", appearance: .dark,
            colors: [
                "#001728", "#002C4D", "#FFFFFF", "#A8C1FF", "#00E2FF", "#F84141",
                "#FF6B17", "#FEFF7F", "#63BA89", "#6AB7FB", "#C58AFA", "#FF5DB3"
            ]),
        RaycastTheme(
            name: "Darkstar", author: "stelo", appearance: .dark,
            colors: [
                "#000000", "#000527", "#FFE5E5", "#FFCACA", "#FFA2A2", "#E54F57",
                "#EC875C", "#DAAA3F", "#58AB5A", "#539BF5", "#786EF8", "#F85FD7"
            ]),
        RaycastTheme(
            name: "Doom One Dark", author: "Simon", appearance: .dark,
            colors: [
                "#282C34", "#282C34", "#BBC2CF", "#BBC2CF", "#BBC2CF", "#FF5458",
                "#F88D4E", "#ECBE7B", "#98BE65", "#51AFEF", "#C678DD", "#C678DD"
            ]),
        RaycastTheme(
            name: "Dracula", author: "Per Tikær", appearance: .dark,
            colors: [
                "#282A36", "#282A36", "#F8F8F2", "#BD93F9", "#BD93F9", "#FF5555",
                "#FFB86C", "#F1FA8C", "#50FA7B", "#8BE9FD", "#BD93F9", "#FF79C6"
            ]),
        RaycastTheme(
            name: "Dragon Fire", author: "Rúben Gomes", appearance: .dark,
            colors: [
                "#000000", "#910000", "#F2F2F2", "#FF0000", "#FF0000", "#F82D2D",
                "#F8762A", "#FFC93B", "#26F894", "#3394F6", "#6834F8", "#F839B6"
            ]),
        RaycastTheme(
            name: "Dusk", author: "Daniel Hollick", appearance: .light,
            colors: [
                "#FFF6E4", "#FFD7FB", "#000966", "#DA69FF", "#9F00FF", "#F87B7B",
                "#FFAC7E", "#FFF7A2", "#65BD96", "#768DFF", "#B385EC", "#FF82C5"
            ]),
        RaycastTheme(
            name: "Dusk", author: "Thomas Novaro", appearance: .dark,
            colors: [
                "#545E75", "#2A2A2A", "#F2F2F2", "#4DE1E0", "#FF6B6B", "#E44848",
                "#DB7C45", "#DDB13E", "#59D298", "#4B98E4", "#6C45DA", "#D643A3"
            ]),
        RaycastTheme(
            name: "Ember", author: "Stephen Kaplan", appearance: .dark,
            colors: [
                "#D23F00", "#A80000", "#F2F2F2", "#F84E4E", "#FFFFFF", "#F84E4E",
                "#F88D4E", "#FFCC47", "#4EF8A7", "#228CF6", "#7B4EF8", "#F84EBD"
            ]),
        RaycastTheme(
            name: "Everforest", author: "Sam-Ashley", appearance: .dark,
            colors: [
                "#272E33", "#272E33", "#D3C6AA", "#FFFFFF", "#FFFFFF", "#E67E80",
                "#E69875", "#DBBC7F", "#A7C080", "#7FBBB3", "#D699B6", "#CF2F98"
            ]),
        RaycastTheme(
            name: "Forest", author: "Michael Schultz", appearance: .dark,
            colors: [
                "#00241E", "#00241E", "#C8F2DB", "#C8F2DB", "#83B198", "#F84E4E",
                "#F88D4E", "#FFCC47", "#4EF8A7", "#228CF6", "#7B4EF8", "#F84EBD"
            ]),
        RaycastTheme(
            name: "Fresh Ocean", author: "Per Tikær", appearance: .light,
            colors: [
                "#FFFFFF", "#3CA3B4", "#002547", "#123237", "#3CA3B4", "#F84E4E",
                "#F88D4E", "#FFCC47", "#4EF8A7", "#228CF6", "#7B4EF8", "#F84EBD"
            ]),
        RaycastTheme(
            name: "GitHub Dark", author: "Marlon", appearance: .dark,
            colors: [
                "#0C1116", "#0C1116", "#E6EDF4", "#A5ADB8", "#4E91FC", "#E54F57",
                "#EC875C", "#DAAA3F", "#58AB5A", "#539BF5", "#786EF8", "#F85FD7"
            ]),
        RaycastTheme(
            name: "GitHub Dark Dimmed", author: "Marlon", appearance: .dark,
            colors: [
                "#22272E", "#22272E", "#AEBAC7", "#B7BEC7", "#4E91FC", "#E54F57",
                "#EC875C", "#DAAA3F", "#58AB5A", "#539BF5", "#786EF8", "#F85FD7"
            ]),
        RaycastTheme(
            name: "GitHub Light", author: "Robert", appearance: .light,
            colors: [
                "#F6F8FA", "#F6F8FA", "#1F2328", "#0969DA", "#D0D7DE", "#CF222E",
                "#BC4C00", "#D4A72C", "#1A7F37", "#0969DA", "#8250DF", "#BF3989"
            ]),
        RaycastTheme(
            name: "Gradient Solarised", author: "Daniel", appearance: .light,
            colors: [
                "#FDFF73", "#E99C40", "#000000", "#000000", "#000000", "#FD3131",
                "#F2894C", "#FFCC47", "#4EF8A7", "#228CF6", "#7B4EF8", "#F84EBD"
            ]),
        RaycastTheme(
            name: "Greenish", author: "Daniel Hollick", appearance: .light,
            colors: [
                "#B9FCEC", "#77FFCB", "#034E7C", "#00A4D3", "#030303", "#EC3A3A",
                "#FF833C", "#FFB000", "#16B544", "#4668D8", "#B56CE3", "#F50AA3"
            ]),
        RaycastTheme(
            name: "Gruvbox", author: "Per Tikær", appearance: .dark,
            colors: [
                "#282828", "#282828", "#EBDBB2", "#A89984", "#EBDBB2", "#CC241D",
                "#D65D0E", "#D79921", "#98971A", "#458588", "#D3869B", "#B16286"
            ]),
        RaycastTheme(
            name: "Guava", author: "Lex", appearance: .dark,
            colors: [
                "#825C84", "#6996A6", "#B7D7C5", "#B7D7C5", "#FFFFFF", "#F84E4E",
                "#F88D4E", "#FFCC47", "#4EF8A7", "#228CF6", "#7B4EF8", "#F84EBD"
            ]),
        RaycastTheme(
            name: "Jahir Light", author: "Jahir", appearance: .light,
            colors: [
                "#EBF0FB", "#D7E1F7", "#0B152B", "#3867D6", "#3867D6", "#EB3B5A",
                "#FA8231", "#E29C09", "#20BF6B", "#2D98DA", "#6C5CE7", "#F368E0"
            ]),
        RaycastTheme(
            name: "Kanagawa", author: "Steve Simkins", appearance: .dark,
            colors: [
                "#1F1F27", "#1F1F27", "#F2F2F2", "#FFFFFF", "#FFFFFF", "#C34043",
                "#FFA066", "#DCA561", "#76946A", "#7FB4CA", "#7B4EF8", "#F84EBD"
            ]),
        RaycastTheme(
            name: "Knight Rider", author: "Thomas Paul Mann", appearance: .dark,
            colors: [
                "#030303", "#030303", "#F2F2F2", "#FFFFFF", "#F84E4E", "#F84E4E",
                "#F88D4E", "#FFCC47", "#4EF8A7", "#228CF6", "#7B4EF8", "#F84EBD"
            ]),
        RaycastTheme(
            name: "La Rosa (Light)", author: "Noah Raskin", appearance: .light,
            colors: [
                "#E7F3FE", "#FFEBF5", "#1F2331", "#D14890", "#FFFFFF", "#E77575",
                "#E8864D", "#D7B20E", "#63C093", "#6581CA", "#7E64C8", "#F881CF"
            ]),
        RaycastTheme(
            name: "Lakers", author: "Marlon", appearance: .dark,
            colors: [
                "#150128", "#474323", "#C4B7D0", "#BFA2DD", "#FFC995", "#E53C71",
                "#F8A26F", "#FFD25B", "#68CF9E", "#438ED6", "#926DF8", "#FF70CD"
            ]),
        RaycastTheme(
            name: "Light Owl", author: "Vyacheslav Pukhanov", appearance: .light,
            colors: [
                "#FBFBFB", "#FBFBFB", "#403F53", "#4B4B4B", "#4B4B4B", "#DE3B3B",
                "#DA6C01", "#E1C502", "#08916A", "#288ED7", "#A143D6", "#D6438A"
            ]),
        RaycastTheme(
            name: "Linear Theme", author: "Noah Raskin", appearance: .dark,
            colors: [
                "#080A1D", "#080A1D", "#F2F2F2", "#767AF2", "#575BC7", "#F84E4E",
                "#F88D4E", "#FFCC47", "#4EF8A7", "#228CF6", "#7B4EF8", "#F84EBD"
            ]),
        RaycastTheme(
            name: "Martinique", author: "Mathieu de Gouville", appearance: .dark,
            colors: [
                "#00160A", "#23201E", "#E7FFF2", "#EF1923", "#EF1923", "#EF1923",
                "#F26522", "#FFC20E", "#00DB6A", "#0072BC", "#92278F", "#E6007E"
            ]),
        RaycastTheme(
            name: "Mistallic", author: "Noah Raskin", appearance: .dark,
            colors: [
                "#1E1E1E", "#4C4C4C", "#F2F2F2", "#D5D5D5", "#CDD0E2", "#FF6868",
                "#CDD0E2", "#CDD0E2", "#CDD0E2", "#CDD0E2", "#CDD0E2", "#D1D7F8"
            ]),
        RaycastTheme(
            name: "Modus Operandi", author: "Ivan Tomica", appearance: .light,
            colors: [
                "#FFFFFF", "#FFFFFF", "#000000", "#BDBDBD", "#0031A9", "#A60000",
                "#884900", "#6F5500", "#006800", "#0031A9", "#531AB6", "#721045"
            ]),
        RaycastTheme(
            name: "Modus Vivendi", author: "Ivan Tomica", appearance: .dark,
            colors: [
                "#000000", "#000000", "#FFFFFF", "#5A5A5A", "#2FAFFF", "#FF5F59",
                "#FEC43F", "#D0BC00", "#44BC44", "#2FAFFF", "#B6A0FF", "#FEACD0"
            ]),
        RaycastTheme(
            name: "Monochrome", author: "Astrit", appearance: .dark,
            colors: [
                "#000000", "#000000", "#F2F2F2", "#FFFFFF", "#FFFFFF", "#FFFFFF",
                "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF"
            ]),
        RaycastTheme(
            name: "Monokai Spectrum", author: "Izak Jackson", appearance: .dark,
            colors: [
                "#000000", "#111111", "#F7F1FF", "#FC618D", "#FCE566", "#FC618D",
                "#FD9353", "#FCE566", "#7BD88F", "#5AD4E6", "#948AE3", "#FC618D"
            ]),
        RaycastTheme(
            name: "Monokai Sun", author: "Tony Keiser", appearance: .light,
            colors: [
                "#F8EFE7", "#EEE5DE", "#111111", "#92898A", "#00C7BE", "#CE4770",
                "#D45E2B", "#B16803", "#218871", "#2473B6", "#6851A2", "#00C7BE"
            ]),
        RaycastTheme(
            name: "Nadeshiko", author: "M.Y.", appearance: .light,
            colors: [
                "#DC9FB4", "#DC9FB4", "#000000", "#DC2F6A", "#000000", "#F84E4E",
                "#F88D4E", "#FFCC47", "#4EF8A7", "#228CF6", "#7B4EF8", "#F84EBD"
            ]),
        RaycastTheme(
            name: "Night Owl", author: "Vyacheslav Pukhanov", appearance: .dark,
            colors: [
                "#011627", "#011627", "#D6DEEB", "#99B7B7", "#99B7B7", "#EF5050",
                "#F77D49", "#FFE98A", "#6FDA9B", "#50A2E4", "#9A6AED", "#C07FEA"
            ]),
        RaycastTheme(
            name: "Night Rose", author: "Rúben Gomes", appearance: .dark,
            colors: [
                "#000000", "#190013", "#F2F2F2", "#FF4081", "#F992D3", "#F84E4E",
                "#F88D4E", "#FFCC47", "#4EF8A7", "#228CF6", "#7B4EF8", "#F84EBD"
            ]),
        RaycastTheme(
            name: "Nord Dark", author: "Joshua Burri", appearance: .dark,
            colors: [
                "#2E3440", "#3B4252", "#ECEFF4", "#ECEFF4", "#ECEFF4", "#BF616A",
                "#D08D70", "#EBCB8B", "#A3BE8C", "#5E81AC", "#CD97C3", "#C766A5"
            ]),
        RaycastTheme(
            name: "Nord Light", author: "Joshua Burri", appearance: .light,
            colors: [
                "#ECEFF4", "#D8DEE9", "#2E3440", "#2E3440", "#2E3440", "#BF616A",
                "#D08D70", "#EBCB8B", "#A3BE8C", "#5E81AC", "#CD97C3", "#C766A5"
            ]),
        RaycastTheme(
            name: "Oceanic Bliss", author: "Thomas Lombart", appearance: .dark,
            colors: [
                "#0C519B", "#000F20", "#E0EFFF", "#60A7E6", "#60A7E6", "#FF6B6B",
                "#FFE66D", "#96E6B3", "#7FD1B9", "#80A1C1", "#A89AC1", "#FFA3D1"
            ]),
        RaycastTheme(
            name: "Palenight", author: "Barry", appearance: .dark,
            colors: [
                "#2A2D3D", "#2A2D3D", "#C0C7D4", "#856ACF", "#89DDFF", "#F07178",
                "#DD9373", "#FFCB6B", "#C3E88D", "#82AAFF", "#856ACF", "#C792EA"
            ]),
        RaycastTheme(
            name: "Poimandres", author: "Izak Jackson", appearance: .dark,
            colors: [
                "#1B1E28", "#303340", "#FFFFFF", "#ADD7FF", "#5DE4C7", "#FF8181",
                "#FFBE6F", "#FFFBC2", "#5DE4C6", "#89DDFF", "#D0679D", "#FDC5E9"
            ]),
        RaycastTheme(
            name: "Polar Night", author: "Luis Filipe", appearance: .dark,
            colors: [
                "#4C566A", "#4C566A", "#EDEFF4", "#92BBCB", "#D8DEE9", "#BF616A",
                "#D08D70", "#EBCB8B", "#A3BE8C", "#228CF6", "#B48EAD", "#F8AFDF"
            ]),
        RaycastTheme(
            name: "Purple Mist", author: "Tarik", appearance: .dark,
            colors: [
                "#553B90", "#25193E", "#FAF6DC", "#FFBC9F", "#ECFB23", "#F84E4E",
                "#F88D4E", "#FFCC47", "#4EF8A7", "#228CF6", "#7B4EF8", "#F84EBD"
            ]),
        RaycastTheme(
            name: "Purple Puke", author: "Daniel", appearance: .dark,
            colors: [
                "#000000", "#2B1F36", "#E4C6FF", "#E0ABFF", "#9430FF", "#F50A0A",
                "#F5600A", "#E0A200", "#07BA65", "#0A7FF5", "#B00AFF", "#F50AA3"
            ]),
        RaycastTheme(
            name: "RAIcast", author: "Rob Hewitt", appearance: .dark,
            colors: [
                "#000000", "#7D3030", "#F2F2F2", "#FFAEAE", "#FF6363", "#F84E4E",
                "#F88D4E", "#FFCC47", "#4EF8A7", "#228CF6", "#7B4EF8", "#F84EBD"
            ]),
        RaycastTheme(
            name: "Raycast Dark - Purple", author: "Vatsal Sanjay", appearance: .dark,
            colors: [
                "#68246D", "#030303", "#F2F2F2", "#FFFFFF", "#FFFFFF", "#F84E4E",
                "#F88D4E", "#FFCC47", "#4EF8A7", "#228CF6", "#7B4EF8", "#F84EBD"
            ]),
        RaycastTheme(
            name: "Raycast Total Grey", author: "Jag_k", appearance: .dark,
            colors: [
                "#030303", "#030303", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#868686",
                "#9B9B9B", "#B0B0B0", "#A4A4A4", "#8C8C8C", "#959595", "#ABABAB"
            ]),
        RaycastTheme(
            name: "Red Boy", author: "Pedro Duarte", appearance: .light,
            colors: [
                "#FFFFFF", "#FFFFFF", "#FF0000", "#FF0000", "#FF0000", "#E14848",
                "#E5753C", "#B7B400", "#00AC5D", "#4F80FF", "#9454FF", "#D756BF"
            ]),
        RaycastTheme(
            name: "Rikyucha", author: "M Yano", appearance: .light,
            colors: [
                "#6D5400", "#6D5400", "#000000", "#896900", "#000000", "#F84E4E",
                "#F88D4E", "#FFCC47", "#4EF8A7", "#228CF6", "#7B4EF8", "#F84EBD"
            ]),
        RaycastTheme(
            name: "Rosé Pine Moon", author: "Zander", appearance: .dark,
            colors: [
                "#232136", "#232136", "#E0DEF4", "#908CAA", "#6E6A86", "#EB6F7F",
                "#F88D4E", "#F6C177", "#9CCFD8", "#3E8FB0", "#B286E7", "#EB6FB9"
            ]),
        RaycastTheme(
            name: "Sequoia Monochrome Dark", author: "Micheal Andreuzza", appearance: .dark,
            colors: [
                "#0F1014", "#111216", "#868690", "#B6BAC8", "#B6BAC8", "#999EB2",
                "#B6BAC8", "#D3D5DE", "#626983", "#7C829D", "#D3D5DE", "#E2E4ED"
            ]),
        RaycastTheme(
            name: "Sequoia Monochrome Light", author: "Micheal Andreuzza", appearance: .light,
            colors: [
                "#EDEEF2", "#E2E3E8", "#282930", "#454752", "#454752", "#525666",
                "#454752", "#50535E", "#2E3038", "#5F6370", "#50535E", "#25262D"
            ]),
        RaycastTheme(
            name: "Sequoia Moonlight Dark", author: "Micheal Andreuzza", appearance: .dark,
            colors: [
                "#0F1014", "#111216", "#868690", "#FFBB88", "#FFBB88", "#F58EE0",
                "#FFBB88", "#9898A6", "#8EB6F5", "#C58FFF", "#9898A6", "#FDFDFE"
            ]),
        RaycastTheme(
            name: "Sequoia Moonlight Light", author: "Micheal Andreuzza", appearance: .light,
            colors: [
                "#EDEEF2", "#E2E3E8", "#282930", "#D9884A", "#D9884A", "#C94DA8",
                "#D9884A", "#6A6A78", "#4A85D4", "#9A5FD9", "#6A6A78", "#282930"
            ]),
        RaycastTheme(
            name: "Sequoia Retro Dark", author: "Micheal Andreuzza", appearance: .dark,
            colors: [
                "#0F1014", "#111216", "#868690", "#A27E57", "#A27E57", "#829FA7",
                "#A27E57", "#DA674B", "#648F68", "#5C87A4", "#DA674B", "#E8B246"
            ]),
        RaycastTheme(
            name: "Sequoia Retro Light", author: "Micheal Andreuzza", appearance: .light,
            colors: [
                "#EDEEF2", "#E2E3E8", "#282930", "#8A6539", "#8A6539", "#5F7982",
                "#8A6539", "#BF5238", "#4A704E", "#456A82", "#BF5238", "#C99730"
            ]),
        RaycastTheme(
            name: "Serendipity Midnight", author: "Micheal Andreuzza", appearance: .dark,
            colors: [
                "#151726", "#1C1E2D", "#DEE0EF", "#F8D2C9", "#F8D2C9", "#EE8679",
                "#F8D2C9", "#A78BFA", "#5BA2D0", "#94B8FF", "#A78BFA", "#9CCFD8"
            ]),
        RaycastTheme(
            name: "Serendipity Morning", author: "Micheal Andreuzza", appearance: .light,
            colors: [
                "#F6F7FB", "#EAEBEE", "#3F4363", "#E58678", "#E58678", "#C25A4D",
                "#E58678", "#785FD0", "#2F7AAB", "#6288D8", "#785FD0", "#629AA5"
            ]),
        RaycastTheme(
            name: "Serendipity Sunset", author: "Micheal Andreuzza", appearance: .dark,
            colors: [
                "#202231", "#272938", "#DEE0EF", "#D6B4B4", "#D6B4B4", "#D1918F",
                "#D6B4B4", "#A392DC", "#709BBD", "#A0B6E8", "#A392DC", "#AAC9D4"
            ]),
        RaycastTheme(
            name: "Shades of Purple", author: "Kevin Batdorf", appearance: .dark,
            colors: [
                "#2D2B56", "#2D2B56", "#E1EFFF", "#FB94FF", "#FB94FF", "#FF628C",
                "#FF9D00", "#FAD000", "#A5FF90", "#9EFFFF", "#FB94FF", "#FF628C"
            ]),
        RaycastTheme(
            name: "Slatewave", author: "Kevin Langley Jr", appearance: .dark,
            colors: [
                "#282C34", "#1E293B", "#E2E8F0", "#5EEAD4", "#5EEAD4", "#FB7185",
                "#FF4500", "#FBBF24", "#5EEAD4", "#38BDF8", "#B388FF", "#F472B6"
            ]),
        RaycastTheme(
            name: "Snow Storm", author: "Luis Filipe", appearance: .light,
            colors: [
                "#ECEFF4", "#ECEFF4", "#4E5568", "#6680A9", "#4C566A", "#BF616A",
                "#D08D70", "#EBCB8B", "#A3BE8C", "#228CF6", "#B48EAD", "#F8AFDF"
            ]),
        RaycastTheme(
            name: "Solarised", author: "Daniel Hollick", appearance: .light,
            colors: [
                "#F0ECCF", "#F0F0F0", "#000000", "#5B5000", "#F1F400", "#DA404C",
                "#D98F26", "#E4C900", "#6CD04D", "#0059C8", "#8B25FF", "#B624C8"
            ]),
        RaycastTheme(
            name: "Sonoma Dark", author: "Iliyan Kupenov", appearance: .dark,
            colors: [
                "#272727", "#272727", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#EB7745",
                "#F2A33C", "#F9D84A", "#6BD45F", "#3B82F7", "#B260EA", "#EB4B63"
            ]),
        RaycastTheme(
            name: "Sonoma Light", author: "Iliyan Kupenov", appearance: .light,
            colors: [
                "#E6E6E6", "#E6E6E6", "#333333", "#333333", "#333333", "#EB713D",
                "#F19A37", "#F7CE46", "#63CA56", "#3478F6", "#A357D7", "#EB4B63"
            ]),
        RaycastTheme(
            name: "Spotify", author: "Pedro Duarte", appearance: .dark,
            colors: [
                "#121212", "#121212", "#FFFFFF", "#00FF5A", "#28FF74", "#F50A0A",
                "#F5600A", "#E0A200", "#07BA65", "#0A7FF5", "#470AF5", "#F50AA3"
            ]),
        RaycastTheme(
            name: "Submarine", author: "Daniel Hollick", appearance: .dark,
            colors: [
                "#001068", "#00685E", "#EAFBFF", "#00FFEA", "#D6AEFF", "#F87E7E",
                "#FFB765", "#FEFF7F", "#7EECAE", "#72BAFB", "#CE9DFA", "#FFA2D4"
            ]),
        RaycastTheme(
            name: "SynthGreen '86", author: "Kevin Ridgway", appearance: .dark,
            colors: [
                "#262335", "#262335", "#BBBBBB", "#00FF61", "#D6FCB9", "#FF9C72",
                "#FF8B39", "#FEFDC2", "#B4FA72", "#A5D5FE", "#A788FF", "#FF8FFD"
            ]),
        RaycastTheme(
            name: "SynthGreen '86 Light", author: "Kevin Ridgway", appearance: .light,
            colors: [
                "#F6F6F6", "#F6F6F6", "#646464", "#00FF61", "#42E622", "#FF9C72",
                "#FF8B39", "#D2CF38", "#85B954", "#7597B4", "#7C65BD", "#C770C6"
            ]),
        RaycastTheme(
            name: "Synthwave '84 Neon", author: "Kevin Batdorf", appearance: .dark,
            colors: [
                "#262335", "#262335", "#BBBBBB", "#F92AAD", "#F92AAD", "#FC1F2C",
                "#FF8B39", "#F39F05", "#72F1B8", "#03EDF9", "#7447F5", "#F92AAD"
            ]),
        RaycastTheme(
            name: "Terminal", author: "Per Tikær", appearance: .dark,
            colors: [
                "#000000", "#000000", "#4AF626", "#4AF626", "#4AF626", "#4AF626",
                "#4AF626", "#4AF626", "#4AF626", "#4AF626", "#4AF626", "#4AF626"
            ]),
        RaycastTheme(
            name: "Tokyo Neon", author: "Sean Rose", appearance: .dark,
            colors: [
                "#000000", "#340087", "#FFFFFF", "#FF4081", "#00E5FF", "#FF1744",
                "#FF9100", "#FFEA00", "#69F0AE", "#00B0FF", "#5C6BC0", "#F50057"
            ]),
        RaycastTheme(
            name: "Tokyo Night", author: "Folke", appearance: .dark,
            colors: [
                "#292E42", "#0C0E14", "#C0CAF5", "#7AA2F7", "#FF9E64", "#F7768E",
                "#FF9E64", "#E0AF68", "#9ECE6A", "#7AA2F7", "#9D7CD8", "#FF007C"
            ]),
        RaycastTheme(
            name: "Tokyo Night Storm", author: "Locke", appearance: .dark,
            colors: [
                "#24283B", "#1D202F", "#C0CAF5", "#7AA2F7", "#FF9E64", "#F7768E",
                "#FF9E64", "#E0AF68", "#9ECE6A", "#7AA2F7", "#7DCFFF", "#BB9AF7"
            ]),
        RaycastTheme(
            name: "Toothpaste", author: "Juan Banchero", appearance: .dark,
            colors: [
                "#222E33", "#222E33", "#DAE3E8", "#739AAB", "#FFFFFF", "#CC6666",
                "#C88E4B", "#DBCD7F", "#9DC777", "#769EB3", "#9B82C9", "#C5487A"
            ]),
        RaycastTheme(
            name: "Turtley Awesome", author: "Lepidox", appearance: .dark,
            colors: [
                "#003C5D", "#006755", "#E0EAF5", "#E0EAF5", "#00E1BA", "#ED5959",
                "#ED8659", "#EDD559", "#47FF91", "#1A9FFF", "#7759ED", "#ED59B2"
            ]),
        RaycastTheme(
            name: "Vesper", author: "Dmytro Ulianov", appearance: .dark,
            colors: [
                "#101010", "#101010", "#FFFFFF", "#FFC799", "#FFC799", "#FF8282",
                "#FFC799", "#FFF499", "#99FFE4", "#99BDFF", "#E899FF", "#FF83CE"
            ]),
        RaycastTheme(
            name: "Vesper dark", author: "Igor Bedesqui", appearance: .dark,
            colors: [
                "#101010", "#101010", "#F2F2F2", "#FFFFFF", "#FFFFFF", "#F84E4E",
                "#FFC799", "#FFCC47", "#99FFE4", "#228CF6", "#7B4EF8", "#F84EBD"
            ]),
        RaycastTheme(
            name: "Vesper dark orange only", author: "Igor Bedesqui", appearance: .dark,
            colors: [
                "#101010", "#101010", "#F2F2F2", "#FFFFFF", "#FFFFFF", "#FFC799",
                "#FFC799", "#FFC799", "#FFC799", "#FFC799", "#FFC799", "#FFC799"
            ]),
        RaycastTheme(
            name: "xgeeks Dark", author: "Joana Santos", appearance: .dark,
            colors: [
                "#5151E5", "#43CBFF", "#F5F5F5", "#92BBCB", "#43CBFF", "#E14848",
                "#E5753C", "#B7B400", "#00AC5D", "#4F80FF", "#9454FF", "#D756BF"
            ]),
        RaycastTheme(
            name: "xgeeks Light", author: "Joana Santos", appearance: .light,
            colors: [
                "#43CBFF", "#5151E5", "#000000", "#9191A5", "#5151E5", "#E14848",
                "#E5753C", "#FFCC47", "#00AC5D", "#4F80FF", "#9454FF", "#D756BF"
            ]),
        RaycastTheme(
            name: "Yankees Blue", author: "Thiago Holanda", appearance: .dark,
            colors: [
                "#4462AF", "#223344", "#D7F0F4", "#6688FF", "#47FFFF", "#ED5959",
                "#ED8659", "#EDD559", "#47FF91", "#1A9FFF", "#7759ED", "#ED59B2"
            ]),
        RaycastTheme(
            name: "Yellow Plastic MI", author: "Tarik", appearance: .light,
            colors: [
                "#DCE0B8", "#DCE0B8", "#0D0D0D", "#777A64", "#A862CD", "#F50A0A",
                "#F5600A", "#E0A200", "#07BA65", "#0A7FF5", "#470AF5", "#F50AA3"
            ]),
    ]
}
